#!/usr/bin/env bash
# HTH Pack Contract: v1
#   control: notion-2.3
#   guide:   https://howtoharden.com/guides/notion/#23-limit-admin-access
#   profile: L1
#   mode:    read-only
#   requires: NOTION_SCIM_TOKEN(Enterprise SCIM API token, generated by an organization owner), MAX_OWNERS(optional, default 3)
# =============================================================================
# HTH Notion Control 2.3: Limit Admin Access
# Profile: L1 | CIS Controls: 5.4 | NIST 800-53: AC-6(1)
# Dependencies: curl, jq
#
# Inventories workspace owners through Notion's SCIM API and flags a workspace
# with more owners than MAX_OWNERS. Notion's public REST API (/v1/users) does
# not return workspace roles; the SCIM API does, in the Notion user-schema
# extension attribute "role" ("owner" | "membership_admin" | "member" |
# "restricted_member"). The same attribute is the write surface: a PATCH/PUT
# of /Users/<id> setting role to "member" demotes an owner. This pack only reads.
# Endpoint: GET https://api.notion.com/scim/v2/Users (startIndex is 1-indexed,
# count max 100). Auth: the SCIM API token as a Bearer token.
# Docs: https://www.notion.com/help/provision-users-and-groups-with-scim
#       https://www.notion.com/help/set-up-identity-provider-for-scim
# Plan: Enterprise only — "Only Enterprise Plan organization owners can
# generate and view SCIM API tokens"; one token per workspace.
#
# Fail-closed: any non-200 response, a body without the SCIM ListResponse
# shape, zero users, zero owners, or any active user returned without the role
# attribute (owners could be undercounted) is a precondition / INCONCLUSIVE,
# never PASS.
# Exit codes: 0 compliant | 1 finding | 2 precondition / inconclusive
# =============================================================================
set -euo pipefail

[ -n "${NOTION_SCIM_TOKEN:-}" ] || { echo "PRECONDITION: set NOTION_SCIM_TOKEN — a Notion SCIM API token (Enterprise; Manage organization → General → SCIM provisioning)" >&2; exit 2; }
MAX_OWNERS="${MAX_OWNERS:-3}"
[[ "${MAX_OWNERS}" =~ ^[1-9][0-9]*$ ]] || { echo "PRECONDITION: MAX_OWNERS must be a positive integer" >&2; exit 2; }
command -v curl >/dev/null 2>&1 || { echo "PRECONDITION: curl not found" >&2; exit 2; }
command -v jq   >/dev/null 2>&1 || { echo "PRECONDITION: jq not found" >&2; exit 2; }

BODY_FILE="$(mktemp "${TMPDIR:-/tmp}/hth-notion-scim.XXXXXX")"
USERS_FILE="$(mktemp "${TMPDIR:-/tmp}/hth-notion-scim-users.XXXXXX")"
trap 'rm -f "${BODY_FILE}" "${USERS_FILE}"' EXIT

# HTH Guide Excerpt: begin api-audit-workspace-owners
SCIM_BASE="https://api.notion.com/scim/v2"
EXT="urn:ietf:params:scim:schemas:extension:notion:2.0:User"
start=1
calls=0
while :; do
  code=$(curl -sS -o "${BODY_FILE}" -w '%{http_code}' \
    "${SCIM_BASE}/Users?startIndex=${start}&count=100" \
    -H "Authorization: Bearer ${NOTION_SCIM_TOKEN}" \
    -H "Accept: application/scim+json") || code="000"
  if [ "${code}" != "200" ]; then
    echo "PRECONDITION: GET /scim/v2/Users returned HTTP ${code}" >&2
    echo "  401 = invalid or revoked SCIM token; 403/404 = workspace not on the Enterprise Plan or SCIM not set up." >&2
    exit 2
  fi
  if ! jq -e '(.Resources | type == "array") and (.totalResults | type == "number")' "${BODY_FILE}" >/dev/null 2>&1; then
    echo "PRECONDITION: response is not a SCIM ListResponse (no Resources array / totalResults)" >&2
    exit 2
  fi
  page=$(jq '.Resources | length' "${BODY_FILE}")
  jq -c '.Resources[]' "${BODY_FILE}" >> "${USERS_FILE}"
  total=$(jq '.totalResults' "${BODY_FILE}")
  calls=$((calls + 1))
  start=$((start + page))
  [ "${page}" -gt 0 ] && [ "$((start - 1))" -lt "${total}" ] || break
  [ "${calls}" -lt 500 ] || { echo "PRECONDITION: pagination runaway guard hit" >&2; exit 2; }
done

report=$(jq -s --arg ext "${EXT}" '
  [ .[] | select(.active != false) ] as $active
  | {
      n_active: ($active | length),
      no_role:  [ $active[] | select((.[$ext].role // "") == "") | (.userName // .id) ],
      owners:   [ $active[] | select(.[$ext].role == "owner") | "\(.displayName // .name.formatted // "(unnamed)") <\(.userName // .id)>" ],
      admins:   [ $active[] | select(.[$ext].role == "membership_admin") | (.userName // .id) ]
    }
' "${USERS_FILE}")

n_active=$(jq '.n_active' <<<"${report}")
n_no_role=$(jq '.no_role | length' <<<"${report}")
n_owners=$(jq '.owners | length' <<<"${report}")
n_admins=$(jq '.admins | length' <<<"${report}")
echo "${n_active} active member(s): ${n_owners} workspace owner(s), ${n_admins} membership admin(s)"
jq -r '.owners[] | "  owner: \(.)"' <<<"${report}"

if [ "${n_active}" -eq 0 ]; then
  echo "INCONCLUSIVE: SCIM returned zero active members — nothing was audited" >&2
  exit 2
fi
if [ "${n_no_role}" -gt 0 ]; then
  echo "INCONCLUSIVE: ${n_no_role} active member(s) came back without the ${EXT} role attribute — the owner count cannot be trusted" >&2
  exit 2
fi
if [ "${n_owners}" -eq 0 ]; then
  echo "INCONCLUSIVE: no workspace owner returned — every workspace has at least one, so the listing is incomplete" >&2
  exit 2
fi
if [ "${n_owners}" -gt "${MAX_OWNERS}" ]; then
  echo "WARN: ${n_owners} workspace owners exceeds MAX_OWNERS=${MAX_OWNERS}."
  echo "Demote owners who do not need full administrative control to member (control 2.3)."
  exit 1
fi
echo "PASS: ${n_owners} workspace owner(s), within MAX_OWNERS=${MAX_OWNERS}"
# HTH Guide Excerpt: end api-audit-workspace-owners
