# =============================================================================
# HTH Azure DevOps Control 3.1: Implement YAML Pipeline Security
# Profile: L1 | Section: 3.1
# =============================================================================

# HTH Guide Excerpt: begin secure-pipeline-template
# templates/secure-pipeline.yml
parameters:
  - name: environment
    type: string
    values:
      - development
      - staging
      - production

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              version: '8.x'

          - script: dotnet build --configuration Release
            displayName: 'Build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  - stage: SecurityScan
    dependsOn: Build
    jobs:
      - job: Scan
        steps:
          - task: CredScan@3
            displayName: 'Credential Scanner'

          - task: SdtReport@2
            displayName: 'Security Report'

  - stage: Deploy
    dependsOn: SecurityScan
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to ${{ parameters.environment }}"
# HTH Guide Excerpt: end secure-pipeline-template
