# =============================================================================
# HTH Azure DevOps Control 4.2: Enable Credential Scanning
# Profile: L1 | Section: 4.2
# =============================================================================

# HTH Guide Excerpt: begin credential-scanning-pipeline
# azure-pipelines.yml - Credential scanning
trigger:
  - main
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: MicrosoftSecurityDevOps@1
    displayName: 'Microsoft Security DevOps'
    inputs:
      categories: 'secrets,code'

  - task: PublishSecurityAnalysisLogs@3
    condition: always()
# HTH Guide Excerpt: end credential-scanning-pipeline
