# HTH GitHub Control 4.05: Dependency Review Workflow
# Profile: L1 | NIST: SA-12
# Deploy: Copy to .github/workflows/dependency-review.yml in your repository

# HTH Guide Excerpt: begin cli-dependency-review
name: Dependency Review

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Dependency Review
        uses: actions/dependency-review-action@c74b580d73376b7750d3d2a50bfb8adc2c937507
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-2.0, GPL-3.0
# HTH Guide Excerpt: end cli-dependency-review
