# HTH GitHub Control 5.06: OIDC Deployment Workflow (AWS Example)
# Profile: L2 | NIST: IA-2, IA-5(2)
# https://howtoharden.com/guides/github/#52-use-oidc-instead-of-long-lived-credentials
#
# Deploy: Copy to .github/workflows/deploy-aws.yml

# HTH Guide Excerpt: begin cli-oidc-deploy-workflow
name: Deploy to AWS

on:
  push:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: us-east-1
          # No long-lived credentials needed!

      - name: Deploy
        run: |
          aws s3 sync ./build s3://my-bucket/
# HTH Guide Excerpt: end cli-oidc-deploy-workflow
